name: Deploy to Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy to Hosting
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v1
              with:
                host: ssh.cowman.xyz
                private-key: ${{ secrets.COWMAN_SSH_KEY }}

            - name: Checkout master
              run: git checkout master

            - name: Pull from master
              run: git pull origin master
